theme = "simpleton"

[editor]
auto-pairs = false
bufferline = "multiple"
popup-border = "all"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[keys.insert]
"C-[" = "normal_mode"
