# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  imports = [ ];

  users.users.mkline = {
    isNormalUser = true;
    home = "/home/mkline";
    extraGroups = [
      "wheel"
    ];
    shell = pkgs.zsh;
  };
  home-manager.users.mkline = import ./home-manager.nix {
    workBox = true;
    machineFiles = { };
  };
  nix.settings.trusted-users = [ "root" "mkline" ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" ];
    initrd.kernelModules = [ ];
    kernelModules = [ ];
    extraModulePackages = [ ];
    loader = {
      systemd-boot.enable = true;
      systemd-boot.configurationLimit = 5;
      efi.canTouchEfiVariables = true;
    };
  };

  programs.zsh.enable = true;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;
    };
  };

  # See configuration.nix,
  # https://github.com/utmapp/UTM/issues/4644#issuecomment-2900887629
  services.chrony = {
    extraConfig = ''
      refclock RTC /dev/rtc0:utc
      makestep 1 -1
    '';
    # We're syncing _from_ the RTC, not writing to it.
    enableRTCTrimming = false;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/992d0224-d866-41a6-91a5-0261ac75e408";
      fsType = "btrfs";
      options = [ "compress-force=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A6DB-F3B6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s1.useDHCP = lib.mkDefault true;

  virtualisation.rosetta.enable = true;

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "24.11"; # Did you read the comment?

}
