"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { modifiers = ["bold"] }
"ui.selection" = { fg = "white", bg = "black" }
"ui.selection.primary" = { fg = "white", bg = "light-blue" }

"ui.bufferline" = { fg = "black", bg = "light-gray" }
"ui.bufferline.active" = { fg = "white", bg = "light-blue", modifiers = ["bold"] }

"ui.statusline" = { fg = "white", bg = "light-blue" }
"ui.statusline.inactive" = { modifiers = ["dim"] }
"ui.statusline.active" = { fg = "white", modifiers = ["bold"] }

"ui.menu.selected" = { fg = "white", bg = "light-blue" }

"ui.virtual.jump-label" = { fg = "blue" }
"ui.virtual.ruler" = { bg = "light-gray" }
"ui.virtual.whitespace" = { fg = "light-gray" }

"error" = { fg = "red" }
"warning" = { fg = "yellow" }
"info" = { fg = "light-blue" }
"hint" = { fg = "magenta" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }

"diagnostic.error".underline = { color = "red", style = "curl" }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }
"diagnostic.info".underline = { color = "blue", style = "curl" }
"diagnostic.hint".underline = { color = "magenta", style = "line" }

"comment" = { fg = "green" }
"keyword" = { fg = "red", modifiers = ["bold", "dim"] }
"special" = { fg = "red", modifiers = ["bold"] }
"operator" = { fg = "magenta", modifiers = ["bold", "dim"] }
"type" = { fg = "light-blue", modifiers = ["bold"] }
"constant" = { fg = "cyan" }
"variable.builtin" = { fg = "cyan" }
