"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { modifiers = ["bold"] }
"ui.selection" = { fg = "white", bg = "black" }
"ui.selection.primary" = { fg = "white", bg = "light-blue" }

"ui.statusline" = { fg = "white", bg = "light-blue" }
"ui.statusline.inactive" = { modifiers = ["dim"] }
"ui.statusline.active" = { fg = "white", modifiers = ["bold"] }

"ui.virtual.ruler" = { bg = "light-gray" }
"ui.virtual.whitespace" = { fg = "light-gray" }

"error" = { fg = "light-red" }
"warning" = { fg = "light-yellow" }
"info" = { fg = "light-blue" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "yellow" }
"diff.minus" = { fg = "red" }

"diagnostic.error".underline = { color = "red", style = "curl" }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }

"comment" = { fg = "green" }
"keyword" = { fg = "red", modifiers = ["bold", "dim"] }
"special" = { fg = "red", modifiers = ["bold"] }
"operator" = { fg = "magenta", modifiers = ["bold", "dim"] }
"type" = { fg = "light-blue", modifiers = ["bold"] }
